name: DNS Record Fetcher CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython

      # Run DNS Fetcher script
      - name: Run DNS Fetcher
        run: python Dns_Fetcher.py --domain "google.com"

      # Move generated report into docs folder
      - name: Move report to docs folder
        run: |
          mkdir -p docs
          mv report.html docs/index.html

      # Commit & push updated report
      - name: Commit and push report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Update DNS report" || echo "No changes to commit"
          git push
