name: DNS Record Fetcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual run from Actions tab

jobs:
  fetch-dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest stable

      - name: Set up Python
        uses: actions/setup-python@v5  # Latest stable
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests dnspython

      - name: Run DNS fetcher
        run: python dns_fetcher.py

      - name: Upload report
        uses: actions/upload-artifact@v4  # Latest stable
        with:
          name: dns-report
          path: report.html
