name: Run DNS Fetcher

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          pip install --upgrade pip
          # pip install -r requirements.txt  # uncomment if you have dependencies

      - name: Run DNS Fetcher script
        run: python DNS_Fetcher.py
